# Generated by Django 2.1.2 on 2018-12-12 02:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Travel', 'TRAVEL'), ('LYH', 'LYH')], default='Lyh', max_length=6)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 12, 11, 21, 27, 45, 329775))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('bg_image_skinny', models.ImageField(upload_to='images/')),
                ('bg_image_wide', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='blogpost', help_text='This field is for image storage. Try to keep this the same for all images for one blog and different for different blogs.', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.TextField(blank=True, default=None, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
