# Generated by Django 2.1.2 on 2018-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='blog_title',
            field=models.CharField(default='blogpost', help_text='This field is for image storage. Try to keep this the same for all images for one blog and different for different blogs.', max_length=200),
        ),
        migrations.AddField(
            model_name='postimage',
            name='caption',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/<django.db.models.fields.CharField>'),
        ),
    ]
