# Generated by Django 2.1.2 on 2018-10-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181009_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Travel', 'TRAVEL'), ('LYH', 'LYH')], default='Lyh', max_length=6),
        ),
    ]
